# Generated by Django 5.1.6 on 2025-03-10 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplanner', '0002_meal_remove_mealplan_meal_name_mealplan_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='notes',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dietplanner.meal'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20),
        ),
    ]
