# Generated by Django 5.1.6 on 2025-03-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietplanner', '0003_remove_meal_ingredients_remove_meal_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meal',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
